config/routes.rb
Rails.application.routes.draw do

  resources :dashboards, only: [:index]

  resources :imports, only: [:new, :create] do
    get 'confirm', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  enum source: %i[window digitik]

  belongs_to :user
  has_many :tickets
  has_many :representations, through: :tickets

  validates :user, :source, presence: true
end

app/models/representation.rb
class Representation < ApplicationRecord
  belongs_to :spectacle

  validates :spectacle, :start_date, :end_date, :price, presence: true
end

app/models/spectacle.rb
class Spectacle < ApplicationRecord
  has_many :representations

  validates :name, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  enum payment: %i[individual subscription]

  belongs_to :representation
  belongs_to :user
  belongs_to :deal

  validates :representation, :user, :deal, :payment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum gender: %i[male female]

  has_many :deals
  has_many :tickets, through: :deals
  has_many :representations, through: :tickets

  validates :address, :country, :email, :first_name, :last_name, :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index

    #TODO REFACTO
    #call into service ?

    @total_deal = Deal.count
    @uniq_buyer = User.count

    user_with_age = User.where.not(birth_date: nil)

    @average_age = (user_with_age.map{ |u| (DateTime.now - u.birth_date).to_i  / 365}).sum / user_with_age.count if user_with_age.present?
    @average_price = Representation.average(:price).round if Representation.average(:price).present?
    @average_deal = (Deal.includes(:representations).all.map{ |d| d.representations.sum(:price) }.sum) / Deal.count

  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
  end

  def create
    begin
      CsvToDatabaseService.new(import_params).call()

      redirect_to confirm_imports_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.message

      redirect_to new_import_path
    rescue Exception => e
      flash[:error] = e.message

      redirect_to new_import_path
    end
  end

  def confirm
  end

  private

  def import_params
    params.permit(:csv)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/dashboards/index.html.slim
h1 Dashboards

p Total de résérvations : #{@total_deal}
p Total d'acheteurs : #{@uniq_buyer}
p Age moyen des acheteurs: #{ @average_age} ans
p Prix moyen / représentation: #{@average_price} €
p Prix moyen / réservation: #{@average_deal} €

app/views/imports/confirm.html.slim
h1 Imports#confirm
p Success

=link_to "Import", new_import_path

app/views/imports/new.html.slim
h1 Imports
p Import a csv file

= render 'shared/flash_message' if !flash.empty?

= form_tag imports_path, multipart: true do
  = file_field_tag :csv
  = submit_tag "Import data"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title TestSpectacle
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body.d-flex.flex-column
    = render partial: 'shared/header'

    .container-fluid.d-flex.flex-fill
      .row.flex-fill
        .col-2.p-2.sidebar
          = render partial: 'shared/menu'
        .col-10.p-2.content
          = yield

app/views/shared/_flash_message.html.slim
div
  - flash.each do |key, value|
    = content_tag(:div, value, :class => "alert alert-#{key}")

app/views/shared/_header.html.slim
.head
  .row
    .col-12
      span Test RAILS - Spectacle

app/views/shared/_menu.html.slim
.row.menu
  .col-12
    ul
      li = link_to "Dashboard", dashboards_path

      li = link_to "Import", new_import_path